[package]
name = "tla-eval"
description = "Evaluate TLA+ expressions at concrete states"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["tla", "tlaplus", "evaluator", "formal-methods", "specification"]
categories = ["development-tools", "parser-implementations"]
readme = "../../README.md"

[dependencies]
tla-syntax = { path = "../tla-syntax", version = "0.1.0" }

[lints]
workspace = true
